// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkxCbc5wbVGdI-X6hY-vi1ucSq4y6n1c',
    appId: '1:4159327288:web:e809b26836d782e1b1eacd',
    messagingSenderId: '4159327288',
    projectId: 'umkreisel-flutter',
    authDomain: 'umkreisel-flutter.firebaseapp.com',
    storageBucket: 'umkreisel-flutter.firebasestorage.app',
    measurementId: 'G-CT9D47F0MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOs2rN7BrApEhurqH8gNpZp3vdX7Wsps',
    appId: '1:4159327288:android:16e09b15453b6f34b1eacd',
    messagingSenderId: '4159327288',
    projectId: 'umkreisel-flutter',
    storageBucket: 'umkreisel-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMOGr91m2bMmm0BrrUS4V4Wd9upSE_nqE',
    appId: '1:4159327288:ios:0a426204e704eb6bb1eacd',
    messagingSenderId: '4159327288',
    projectId: 'umkreisel-flutter',
    storageBucket: 'umkreisel-flutter.firebasestorage.app',
    iosBundleId: 'com.example.umkreisel.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMOGr91m2bMmm0BrrUS4V4Wd9upSE_nqE',
    appId: '1:4159327288:ios:30363136ddd7ba52b1eacd',
    messagingSenderId: '4159327288',
    projectId: 'umkreisel-flutter',
    storageBucket: 'umkreisel-flutter.firebasestorage.app',
    iosBundleId: 'com.example.umkreisel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGkxCbc5wbVGdI-X6hY-vi1ucSq4y6n1c',
    appId: '1:4159327288:web:a9ef6908e878a8b7b1eacd',
    messagingSenderId: '4159327288',
    projectId: 'umkreisel-flutter',
    authDomain: 'umkreisel-flutter.firebaseapp.com',
    storageBucket: 'umkreisel-flutter.firebasestorage.app',
    measurementId: 'G-Z5RR3T3XKF',
  );
}
